"""Initial

Revision ID: 46aa4cc68bfe
Revises: 2d23c72bd793
Create Date: 2014-03-02 19:36:02.757886

"""

# revision identifiers, used by Alembic.
revision = '46aa4cc68bfe'
down_revision = '2d23c72bd793'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
